// Generated by https://quicktype.io

export interface UserResponse {
    data:  UserApi;
    token: string;
}

export interface UserApi {
    username:  string;
    image:     string;
    email:     string;
    password?:  string;
    _id:       string;
    createdAt?: string;
    updatedAt?: string;
    __v?:       number;
}


// Generated by https://quicktype.io

export interface UserProfile {
    user: User;
    post: Post;
}

export interface Post {
    _id:       string;
    userId:    string;
    title:     string;
    desc:      string;
    image:     string;
    publish:   string;
    cat:       string;
    avaliable: boolean;
    createdAt: string;
    updatedAt: string;
    __v:       number;
}

export interface User {
    _id:       string;
    username:  string;
    image:     string;
    email:     string;
    password:  string;
    createdAt: string;
    updatedAt: string;
    __v:       number;
}
